### ISSUE TITLE
Need Info on creating Span Event and how to handle span in case of recursive method call

### ISSUE THREAD

**Issue by itsprakash84** [mnadeem/boot-opentelemetry-tempo#23]
Hi ,

I would like thank for this creating such a good example.

**Question 1:**
In the below example, I see event start and end are at same place.

Generally 
1. - START an event in the starting of the method call 
2. - END event will be at the ending of the method 
3. - Exception we would say exception, i think "span.recordException" can be used assuming the event will be closed incase of any exception.
4. Log the request and response in the span

Why we need this to know how many request triggered in specific time and also to get the count of pass/fail in one page.

I request you to modify the code to accommodate this. 

```
@WithSpan
    private void doSomeWorkNewSpan() {
		LOGGER.info("Doing some work In New span");
        Span span = Span.current();
 
        span.setAttribute("attribute.a2", "some value");
 
        span.addEvent("app.processing2.start", atttributes("321"));
        span.addEvent("app.processing2.end", atttributes("321"));
    }

```
**Question 2:**

I have a requirement on recursive method call.

Example a hotel will have 100's of room types, incase of any api first 10 will be sent in first call and soon subsequent calls will made to rest of the data.

Typically code implementation

HotelRoomTypes
        getAllRoomTypes:
ContentAPIClient:
          getRoomTypes(id,nextpageKey) - recursive calls

I want to all this to be happen in open span, because as  functionality talks about all room types everything or nothing.
Overall high level picture is getting all Room types and select a room by checking availability and book, I want to Trace the entire flow in one Trace. 

Regards,
Sathya Prakash.

**Comment by mnadeem** [comment]
1) Instrumentation is different from Monitoring. 
2) Learn about [Java instrumentation](https://opentelemetry.io/docs/java/)

Question #1 : Preferred way to to do is to use Prometheus, however it can be done using tracing as well, it would be plain java, Maintain variables ( persist it if durability is required), and keep on incrementing the counter.

Question #2 : This is possible using [Manual instrumentation ](https://opentelemetry.io/docs/java/manual_instrumentation/)


P.S :  You have to do this yourself, it is your business requirement.
