### ISSUE TITLE
Loki container getting exited

### ISSUE THREAD

**Issue by shovii** [mnadeem/boot-opentelemetry-tempo#24]
Docker Container Logs 
`level=error ts=2021-06-25T05:45:01.085827282Z caller=log.go:106 msg="error running loki" err="mkdir /tmp/loki/chunks: permission denied\nerror initialising module: table-manager\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"`

**Comment by gaeljw** [comment]
Same error here (branch 0.17.0_basic):
```
loki_1                       | level=info ts=2021-10-31T10:37:12.73970135Z caller=main.go:130 msg="Starting Loki" version="(version=2.2.0, branch=HEAD, revision=a27c79913)"
loki_1                       | level=info ts=2021-10-31T10:37:12.739967652Z caller=server.go:229 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
loki_1                       | level=error ts=2021-10-31T10:37:12.740223008Z caller=log.go:106 msg="error running loki" err="mkdir /tmp/loki/chunks: permission denied\nerror initialising module: compactor\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/loki/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/loki/pkg/loki/loki.go:220\nmain.main\n\t/src/loki/cmd/loki/main.go:132\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"
```

**Comment by gaeljw** [comment]
Commenting the volume in `loki` services helped to start (data won't be persisted though):
```yaml
# - ./data/loki-data:/tmp/loki
```

**Comment by dimbleby** [comment]
`user: root` in the loki service works around this.

Having said which, I'm not see any trace anywhere anyway; so something else seems to be going wrong...

**Comment by mnadeem** [comment]
https://github.com/mnadeem/boot-opentelemetry-tempo/issues/27 check this if it works
