### ISSUE TITLE
Jeger this race is not available

### ISSUE THREAD

**Issue by waytoharish** [mnadeem/boot-opentelemetry-tempo#29]
Hi I am trying to run the code and not able to find trace in Jager.

boot-otel-tempo-api_1        | [grpc-default-executor-0] WARN io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter - Failed to export spans
boot-otel-tempo-api_1        | io.grpc.StatusRuntimeException: UNKNOWN: DoBatch: InstancesCount <= 0
boot-otel-tempo-api_1        |  at io.grpc.Status.asRuntimeException(Status.java:534)
boot-otel-tempo-api_1        |  at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
boot-otel-tempo-api_1        |  at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
boot-otel-tempo-api_1        |  at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)

Temo also showing the error-
boot-otel-tempo-provider1_1  |  at java.lang.Thread.run(Thread.java:748)
tempo_1                      | level=error ts=2022-01-24T04:12:33.9494974Z caller=log.go:27 msg="pusher failed to consume trace data" err="DoBatch: InstancesCount <= 0"
loki_1                       | level=info ts=2022-01-24T04:12:34.0035513Z caller=table_manager.go:171 msg="uploading tables"
loki_1                       | level=info ts=2022-01-24T04:12:34.0430109Z caller=table_manager.go:208 msg="syncing tables"
tempo_1                      | level=error ts=2022-01-24T04:12:34.1460915Z caller=log.go:27 msg="pusher failed to consume trace data" err="DoBatch: InstancesCount <= 0"
tempo_1                      | level=error ts=2022-01-24T04:12:37.7995944Z caller=log.go:27 msg="pusher failed to consume trace data" err="DoBatch: InstancesCount <= 0"
bo

![image](https://user-images.githubusercontent.com/5119613/150720972-890189e5-d712-4ddb-bb89-0b8e8bc785a0.png)

![image](https://user-images.githubusercontent.com/5119613/150721021-b376841f-8d5f-462c-9b95-244d90b2467b.png)

**Comment by mnadeem** [comment]
It is by design it seems https://github.com/grafana/tempo/issues/505
